package reasoner;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1494167488.owl#artist
 *
 * @version generated on Sun Nov 12 13:55:39 GMT+07:00 2017
 */
public interface artist extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#presents

    Collection getPresents();

    RDFProperty getPresentsProperty();

    boolean hasPresents();

    Iterator listPresents();

    void addPresents(song newPresents);

    void removePresents(song oldPresents);

    void setPresents(Collection newPresents);
}
