package reasoner;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1494167488.owl#history
 *
 * @version generated on Sun Nov 12 13:55:39 GMT+07:00 2017
 */
public interface history extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#like

    int getLike();

    RDFProperty getLikeProperty();

    boolean hasLike();

    void setLike(int newLike);


    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#listening_times

    int getListening_times();

    RDFProperty getListening_timesProperty();

    boolean hasListening_times();

    void setListening_times(int newListening_times);
}
