package reasoner;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1494167488.owl#song
 *
 * @version generated on Sun Nov 12 13:55:39 GMT+07:00 2017
 */
public interface song extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#belongs

    Collection getBelongs();

    RDFProperty getBelongsProperty();

    boolean hasBelongs();

    Iterator listBelongs();

    void addBelongs(tag newBelongs);

    void removeBelongs(tag oldBelongs);

    void setBelongs(Collection newBelongs);


    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#dislike

    int getDislike();

    RDFProperty getDislikeProperty();

    boolean hasDislike();

    void setDislike(int newDislike);


    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#like

    int getLike();

    RDFProperty getLikeProperty();

    boolean hasLike();

    void setLike(int newLike);


    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#listening_times

    int getListening_times();

    RDFProperty getListening_timesProperty();

    boolean hasListening_times();

    void setListening_times(int newListening_times);


    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#presented_by

    Collection getPresented_by();

    RDFProperty getPresented_byProperty();

    boolean hasPresented_by();

    Iterator listPresented_by();

    void addPresented_by(artist newPresented_by);

    void removePresented_by(artist oldPresented_by);

    void setPresented_by(Collection newPresented_by);


    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#similar

    Collection getSimilar();

    RDFProperty getSimilarProperty();

    boolean hasSimilar();

    Iterator listSimilar();

    void addSimilar(song newSimilar);

    void removeSimilar(song oldSimilar);

    void setSimilar(Collection newSimilar);


    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#song_id

    String getSong_id();

    RDFProperty getSong_idProperty();

    boolean hasSong_id();

    void setSong_id(String newSong_id);


    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#title

    String getTitle();

    RDFProperty getTitleProperty();

    boolean hasTitle();

    void setTitle(String newTitle);
}
