package reasoner;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1494167488.owl#user
 *
 * @version generated on Sun Nov 12 13:55:39 GMT+07:00 2017
 */
public interface user extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#has_history

    Collection getHas_history();

    RDFProperty getHas_historyProperty();

    boolean hasHas_history();

    Iterator listHas_history();

    void addHas_history(history newHas_history);

    void removeHas_history(history oldHas_history);

    void setHas_history(Collection newHas_history);


    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#listens

    Collection getListens();

    RDFProperty getListensProperty();

    boolean hasListens();

    Iterator listListens();

    void addListens(song newListens);

    void removeListens(song oldListens);

    void setListens(Collection newListens);
}
