package reasoner.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import reasoner.user;
import reasoner.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1494167488.owl#user
 *
 * @version generated on Sun Nov 12 13:55:39 GMT+07:00 2017
 */
public class Defaultuser extends AbstractCodeGeneratorIndividual
         implements user {

    public Defaultuser(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultuser() {
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#has_history

    public Collection getHas_history() {
        return getPropertyValuesAs(getHas_historyProperty(), history.class);
    }


    public RDFProperty getHas_historyProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#has_history";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHas_history() {
        return getPropertyValueCount(getHas_historyProperty()) > 0;
    }


    public Iterator listHas_history() {
        return listPropertyValuesAs(getHas_historyProperty(), history.class);
    }


    public void addHas_history(history newHas_history) {
        addPropertyValue(getHas_historyProperty(), newHas_history);
    }


    public void removeHas_history(history oldHas_history) {
        removePropertyValue(getHas_historyProperty(), oldHas_history);
    }


    public void setHas_history(Collection newHas_history) {
        setPropertyValues(getHas_historyProperty(), newHas_history);
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#listens

    public Collection getListens() {
        return getPropertyValuesAs(getListensProperty(), song.class);
    }


    public RDFProperty getListensProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#listens";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasListens() {
        return getPropertyValueCount(getListensProperty()) > 0;
    }


    public Iterator listListens() {
        return listPropertyValuesAs(getListensProperty(), song.class);
    }


    public void addListens(song newListens) {
        addPropertyValue(getListensProperty(), newListens);
    }


    public void removeListens(song oldListens) {
        removePropertyValue(getListensProperty(), oldListens);
    }


    public void setListens(Collection newListens) {
        setPropertyValues(getListensProperty(), newListens);
    }
}
