package reasoner.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import reasoner.song;
import reasoner.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1494167488.owl#song
 *
 * @version generated on Sun Nov 12 13:55:39 GMT+07:00 2017
 */
public class Defaultsong extends AbstractCodeGeneratorIndividual
         implements song {

    public Defaultsong(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultsong() {
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#belongs

    public Collection getBelongs() {
        return getPropertyValuesAs(getBelongsProperty(), tag.class);
    }


    public RDFProperty getBelongsProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#belongs";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasBelongs() {
        return getPropertyValueCount(getBelongsProperty()) > 0;
    }


    public Iterator listBelongs() {
        return listPropertyValuesAs(getBelongsProperty(), tag.class);
    }


    public void addBelongs(tag newBelongs) {
        addPropertyValue(getBelongsProperty(), newBelongs);
    }


    public void removeBelongs(tag oldBelongs) {
        removePropertyValue(getBelongsProperty(), oldBelongs);
    }


    public void setBelongs(Collection newBelongs) {
        setPropertyValues(getBelongsProperty(), newBelongs);
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#dislike

    public int getDislike() {
        return getPropertyValueLiteral(getDislikeProperty()).getInt();
    }


    public RDFProperty getDislikeProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#dislike";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasDislike() {
        return getPropertyValueCount(getDislikeProperty()) > 0;
    }


    public void setDislike(int newDislike) {
        setPropertyValue(getDislikeProperty(), new java.lang.Integer(newDislike));
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#like

    public int getLike() {
        return getPropertyValueLiteral(getLikeProperty()).getInt();
    }


    public RDFProperty getLikeProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#like";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasLike() {
        return getPropertyValueCount(getLikeProperty()) > 0;
    }


    public void setLike(int newLike) {
        setPropertyValue(getLikeProperty(), new java.lang.Integer(newLike));
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#listening_times

    public int getListening_times() {
        return getPropertyValueLiteral(getListening_timesProperty()).getInt();
    }


    public RDFProperty getListening_timesProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#listening_times";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasListening_times() {
        return getPropertyValueCount(getListening_timesProperty()) > 0;
    }


    public void setListening_times(int newListening_times) {
        setPropertyValue(getListening_timesProperty(), new java.lang.Integer(newListening_times));
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#presented_by

    public Collection getPresented_by() {
        return getPropertyValuesAs(getPresented_byProperty(), artist.class);
    }


    public RDFProperty getPresented_byProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#presented_by";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPresented_by() {
        return getPropertyValueCount(getPresented_byProperty()) > 0;
    }


    public Iterator listPresented_by() {
        return listPropertyValuesAs(getPresented_byProperty(), artist.class);
    }


    public void addPresented_by(artist newPresented_by) {
        addPropertyValue(getPresented_byProperty(), newPresented_by);
    }


    public void removePresented_by(artist oldPresented_by) {
        removePropertyValue(getPresented_byProperty(), oldPresented_by);
    }


    public void setPresented_by(Collection newPresented_by) {
        setPropertyValues(getPresented_byProperty(), newPresented_by);
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#similar

    public Collection getSimilar() {
        return getPropertyValuesAs(getSimilarProperty(), song.class);
    }


    public RDFProperty getSimilarProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#similar";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSimilar() {
        return getPropertyValueCount(getSimilarProperty()) > 0;
    }


    public Iterator listSimilar() {
        return listPropertyValuesAs(getSimilarProperty(), song.class);
    }


    public void addSimilar(song newSimilar) {
        addPropertyValue(getSimilarProperty(), newSimilar);
    }


    public void removeSimilar(song oldSimilar) {
        removePropertyValue(getSimilarProperty(), oldSimilar);
    }


    public void setSimilar(Collection newSimilar) {
        setPropertyValues(getSimilarProperty(), newSimilar);
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#song_id

    public String getSong_id() {
        return (String) getPropertyValue(getSong_idProperty());
    }


    public RDFProperty getSong_idProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#song_id";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSong_id() {
        return getPropertyValueCount(getSong_idProperty()) > 0;
    }


    public void setSong_id(String newSong_id) {
        setPropertyValue(getSong_idProperty(), newSong_id);
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#title

    public String getTitle() {
        return (String) getPropertyValue(getTitleProperty());
    }


    public RDFProperty getTitleProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#title";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasTitle() {
        return getPropertyValueCount(getTitleProperty()) > 0;
    }


    public void setTitle(String newTitle) {
        setPropertyValue(getTitleProperty(), newTitle);
    }
}
