package reasoner.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import reasoner.history;
import reasoner.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1494167488.owl#history
 *
 * @version generated on Sun Nov 12 13:55:39 GMT+07:00 2017
 */
public class Defaulthistory extends AbstractCodeGeneratorIndividual
         implements history {

    public Defaulthistory(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaulthistory() {
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#like

    public int getLike() {
        return getPropertyValueLiteral(getLikeProperty()).getInt();
    }


    public RDFProperty getLikeProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#like";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasLike() {
        return getPropertyValueCount(getLikeProperty()) > 0;
    }


    public void setLike(int newLike) {
        setPropertyValue(getLikeProperty(), new java.lang.Integer(newLike));
    }



    // Property http://www.owl-ontologies.com/Ontology1494167488.owl#listening_times

    public int getListening_times() {
        return getPropertyValueLiteral(getListening_timesProperty()).getInt();
    }


    public RDFProperty getListening_timesProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1494167488.owl#listening_times";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasListening_times() {
        return getPropertyValueCount(getListening_timesProperty()) > 0;
    }


    public void setListening_times(int newListening_times) {
        setPropertyValue(getListening_timesProperty(), new java.lang.Integer(newListening_times));
    }
}
